DROP TABLE IF EXISTS TBL_BOOKS;

CREATE TABLE TBL_BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  book_name VARCHAR(250) NOT NULL,
  author_name VARCHAR(250) NOT NULL,
  published_date DATE NOT NULL,
  price DOUBLE NOT NULL,
  in_stock VARCHAR(50) 
);
